### ISSUE TITLE
How to change the font for sneaker?

### ISSUE THREAD

**Issue by karanthakakr04** [Hamadakram/Sneaker#13]
Firstly, thank you for this beautiful library. 

My doubt here is how do I change the font of text inside sneaker? I know you have provided us with a snippet of code in which there's this line:
`.setTypeface(Typeface.createFromAsset(this.getAssets(), "font/" + fontName)); // Custom font for title and message`
When I use this as it is in my project it gives me an error at`fontName`. What do I have to do in order to change the font or use this snippet provided by you?
Could you please post an example providing more clarity on this subject?
Any help would be appreciated.

**Comment by Hamadakram** [comment]
`fontName` is the name of the font that you want to use. You have to add your font .ttf file to Assets/font folder in order to use it. For example you added `Roboto.ttf` font, your font name will be `Roboto.ttf`.
