### ISSUE TITLE
Null exception on getLayout()

### ISSUE THREAD

**Issue by mehdi-salehi** [Hamadakram/Sneaker#2]
if (mAutoHide) {
            Handler handler = new Handler();
            handler.removeCallbacks(null);
            handler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    getLayout().startAnimation(AnimationUtils.loadAnimation(getContext(), R.anim.popup_hide));
                    viewGroup.removeView(getLayout());
                }
            }, mDuration);
        }

**Comment by Hamadakram** [comment]
Fixed in version `1.0.3`
