### ISSUE TITLE
iOS fork?

### ISSUE THREAD

**Issue by ravitripathi** [Hamadakram/Sneaker#24]
This is a beautiful library for showing alerts. Will you port it to iOS anytime soon?

**Comment by VivekThummar52** [comment]
don't know much about `iOS` or `swift` language, but this is awesome  [1]NotificationBanner  

[1]https://github.com/Daltron/NotificationBanner

**Comment by VivekThummar52** [comment]
don't know much about `iOS` or `Swift` language, but this is awesome [NotificationBanner][1] (for future reference also)

[1]: https://github.com/Daltron/NotificationBanner
