### ISSUE TITLE
OnSneakerDismissListener no response 

### ISSUE THREAD

**Issue by haife** [Hamadakram/Sneaker#31]
why activity onDismiss() have not executed 
`  Sneaker.with(this)
            .setTitle(getString(R.string.login_success))
            .setMessage(getString(R.string.success))
            .setOnSneakerDismissListener(this)
            .setDuration(5000)
            .sneakSuccess()
`

`   override fun onDismiss() {
        val intent = Intent(this, MainActivity::class.java)
        launchActivity(intent)
    }`

**Comment by Hamadakram** [comment]
Fixed in version 2.0.0
