### ISSUE TITLE
InComplete Alert Message

### ISSUE THREAD

**Issue by VivekThummar52** [Hamadakram/Sneaker#42]
Hey there, i just started using this repo and it's very useful but in some devices alert message is not showing completely as given below: 

![kotlindemo snap](https://user-images.githubusercontent.com/58064452/115404574-15dbd300-a20b-11eb-8f82-9f0708c42c9b.jpg)

Code: 
(In Activity)

    Sneaker
        .with(this)
        .setTitle("Alert!!")
        .setMessage("Internet Connection Not Found")
        .sneakWarning()

is there any solution for this problem??

**Comment by KomalBohra** [comment]
hey any solution for this issue?

**Comment by VivekThummar52** [comment]
can you please look at this lines and try to change `top` and `bottom` values to `0`(may be) because i solved it but can't remember exactly what solution i have tried..

https://github.com/Hamadakram/Sneaker/blob/master/sneaker/src/main/java/com/irozon/sneaker/SneakerView.kt#L54
https://github.com/Hamadakram/Sneaker/blob/master/sneaker/src/main/java/com/irozon/sneaker/SneakerView.kt#L70

if it will not work then please try setting `margin` because i think i tried that solution..

**Comment by VivekThummar** [comment]
hey @KomalBohra, did you tried my solution or not, and if yes then are you able to solve the issue??

**Comment by VivekThummar52** [comment]
If anyone is still getting this error or will stuck into, just make given changes in line number 54 and 70(may be it will not work for every case but for this case it's working)...

`textLayoutParams.setMargins(
 26,
 0,
 26,
 0
)
tvMessage.layoutParams = textLayoutParams`



> can you please look at this lines and try to change `top` and `bottom` values to `0`(may be) because i solved it but can't remember exactly what solution i have tried..
> 
> https://github.com/Hamadakram/Sneaker/blob/master/sneaker/src/main/java/com/irozon/sneaker/SneakerView.kt#L54 https://github.com/Hamadakram/Sneaker/blob/master/sneaker/src/main/java/com/irozon/sneaker/SneakerView.kt#L70
> 
> if it will not work then please try setting `margin` because i think i tried that solution..

**Comment by VivekThummar52** [comment]
Closing issue for now, if anyone will face the same issue even after trying my solution, then fill free to open this again
