### ISSUE TITLE
Error:Could not find com.android.tools.build:gradle:3.0.0-alpha1.

### ISSUE THREAD

**Issue by guobosheng** [Hamadakram/Sneaker#6]
Error:Could not find com.android.tools.build:gradle:3.0.0-alpha1.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/tools/build/gradle/3.0.0-alpha1/gradle-3.0.0-alpha1.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/tools/build/gradle/3.0.0-alpha1/gradle-3.0.0-alpha1.jar
    https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0-alpha1/gradle-3.0.0-alpha1.pom
    https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0-alpha1/gradle-3.0.0-alpha1.jar
Required by:
    project :

**Comment by Hamadakram** [comment]
This is build on Android studio 3.0. Change gradle version 3.0.0-alpha1 to `classpath 'com.android.tools.build:gradle:2.3.2'`
